workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.pingandwink.pingandwink
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Clean and install pods
        script: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod repo update
          pod install --repo-update
          cd ..
      - name: Remove problematic build phase
        script: |
          # Удаляем проблемный Thin Binary скрипт если он есть
          cd ios
          ruby -e "
          require 'xcodeproj'
          project = Xcodeproj::Project.open('Runner.xcodeproj')
          project.targets.each do |target|
            if target.name == 'Runner'
              target.build_phases.each do |phase|
                if phase.respond_to?(:name) && phase.name == 'Thin Binary'
                  phase.remove_from_project
                end
              end
            end
          end
          project.save
          "
          cd ..
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=$CM_BUILD_ID \
            --build-number=$(($(app-store-connect get-latest-build-number "$APP_STORE_APPLE_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration