workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store  # ИСПРАВЛЕНО: для TestFlight нужен app_store
        bundle_identifier: com.pingandwink.pingandwink
      vars:
        ONESIGNAL_APP_ID: "a65a7e49-5606-45dd-b32d-9e12db9f4e72"
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios && pod install
      
      - name: Verify push notification setup
        script: |
          echo "✅ Checking push notification configuration..."
          echo "Entitlements:"
          cat ios/Runner/Runner.entitlements
          echo "Background modes in Info.plist:"
          grep -A 3 UIBackgroundModes ios/Runner/Info.plist || echo "UIBackgroundModes not found"
      
      - name: Flutter build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true  # ДОБАВЛЕНО: автоматическая загрузка в TestFlight
        submit_to_app_store: false
      email:
        recipients:
          - pingandwink@gmail.com  # ИСПРАВЛЕНО: ваш реальный email
        notify:
          success: true
          failure: true

  android-workflow:
    name: Android Build
    instance_type: linux_x2
    max_build_duration: 30
    environment:
      flutter: stable
      vars:
        ONESIGNAL_APP_ID: "a65a7e49-5606-45dd-b32d-9e12db9f4e72"
    
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Build APK
        script: |
          flutter build apk --release
    
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk