name: pingandwink
description: just vibes
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Environment variables
  flutter_dotenv: ^5.1.0

  flutter_local_notifications: ^17.1.2

  path_provider: ^2.1.1 
    
  # Core dependencies
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  
  # Backend
  supabase_flutter: ^2.3.0
  http: ^1.1.0
  
  # Map - FIXED VERSION to avoid API changes
  mapbox_maps_flutter: 2.3.0  # Removed ^ to lock exact version
  
  # Storage and utilities  
  shared_preferences: ^2.2.0
  uuid: ^4.2.2

  device_info_plus: ^10.1.0
  flutter_secure_storage: ^9.0.0
  
  # Geolocation
  geolocator: ^10.0.0

  # UI
  share_plus: ^7.2.1

  qr_flutter: ^4.1.0

  onesignal_flutter: ^5.1.0
  
  url_launcher: ^6.2.0

  flutter_markdown: ^0.7.4

  timezone: ^0.9.2
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true
  
  # Enable localization
  generate: true
  
  # assets
  assets:
    - .env
    - .env.example
    - assets/images/
  
    # Fonts (when needed)
  # fonts:
  #   - family: Orbitron
  #     fonts:
  #       - asset: assets/fonts/Orbitron-Regular.ttf