name: pingandwink
description: chat nearby
publish_to: 'none'
version: 1.0.4+19

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Environment variables
  flutter_dotenv: ^5.2.1

  # Notifications - обновлено для iOS 18 совместимости
  flutter_local_notifications: ^17.2.4

  path_provider: ^2.1.1 
    
  # Core dependencies
  cupertino_icons: ^1.0.6
  intl: ^0.20.2  # ИСПРАВЛЕНО - используем версию требуемую Flutter SDK
  
  # Backend
  supabase_flutter: ^2.3.0
  http: ^1.1.0
  
  # Map - обновляем для privacy manifest
  mapbox_maps_flutter: 2.3.0  # обновлено с 2.3.0
  
  # Storage and utilities  
  shared_preferences: ^2.3.3  # обновлено с ^2.2.0
  uuid: ^4.5.1  # обновлено с ^4.2.2

  # Device info - обновляем для iOS 18
  device_info_plus: ^11.1.1  # обновлено с ^10.1.2
  
  # КРИТИЧНО - обновляем для iOS 18.7
  flutter_secure_storage: ^9.2.2  # добавлен ^ для автообновлений
  
  # Geolocation
  geolocator: ^13.0.2  # обновлено с ^10.1.1

  # UI
  share_plus: ^10.1.3  # обновлено с ^7.2.2

  qr_flutter: ^4.1.0

  # Push notifications
  onesignal_flutter: ^5.2.8  # обновлено с ^5.1.0
  
  # URL launcher
  url_launcher: ^6.3.1  # обновлено с ^6.2.0

  # Markdown
  flutter_markdown: ^0.7.4

  # Timezone
  timezone: ^0.9.4
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true
  
  # Enable localization
  generate: true
  
  # assets
  assets:
    - .env
    - assets/images/